server:
  port: 8080

spring:
  application:
    name: KAFKA-SERVICE
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://kafka-server-0.kafka-server.kafka:9092
      bindings:
        soheeTopic1:
          destination: soheeTopic1