apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-headless
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  clusterIP: None
  ports:
  - name: broker
    port: 9092
    protocol: TCP
  - name: jmx
    port: 5555
    protocol: TCP
