apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: broker
    port: 9092
    protocol: TCP
  - name: prom-jmx
    port: 5556
    protocol: TCP