version: '2'

# 주키퍼와 카프카 서비스를 설정한다
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper1
    hostname: zookeeper-1
    ports:
      - "12181:12181"     # 클라이언트 포트 12181를 bind 한다. 호스트포트:컨테이너포트
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    hostname: kafka-1
    ports:
      - "19092:19092"

    depends_on:             #컨테이너가 시작되는 순서 컨트롤  kafka 수행 이전에 zookeeper-1 수행
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092       # kafka 브로커를 가리키는 사용 가능 주소 목록. kafka는 초기 연결 시 이를 client에게 보냄


      #KAFKA_CREATE_TOPICS: "topic1:3:3"    # Topic명:Partition개수:Replica개수

  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    container_name: kafka2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    container_name: kafka3
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092

# 카프카 매니저 GUI 툴.
  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:latest
    hostname: kafka-manager
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - zookeeper-1
    command: -Dconfig.file=/kafka-manager/conf/application.conf -Dapplication.home=/kafkamanager
    environment:
      ZK_HOSTS: zookeeper-1:12181
      #- APPLICATION_SECRET: letmein
    ports:
      - "9001:9000"
    # network_mode: "host"

