kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: admin
rules:
  - apiGroups: [""] # "" 는 Core API 를 의미합니다.
    resources: ["pods"]
    verbs: ["get", "watch", "list"]