apiVersion: v1
kind: Service
metadata:
  name: kafka-server-headless
  labels:
    app: kafka
    chart: kafka-0.1.0
    heritage: Tiller
spec:
  selector:
    app: kafka
  type: ClusterIP
  clusterIP: None
  ports:
    - name: broker
      port: 9092
      protocol: TCP
    - name: jmx
      port: 5555
      protocol: TCP